import {useMemo,useState} from "react";
import {Area,AreaChart,Bar,BarChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Activity,ArrowUpRight,Bell,Building2,CalendarCheck,ChevronDown,CircleDollarSign,Command,Filter,LayoutDashboard,Menu,MessageSquare,Plus,Search,Settings,Sparkles,Target,Users,Wallet,X} from "lucide-react";

type Lead={id:number;company:string;contact:string;title:string;industry:string;score:number;status:string;value:number;lastActivity:string};
const leads:Lead[]=[
{id:1,company:"Northstar Labs",contact:"Maya Chen",title:"VP Growth",industry:"SaaS",score:96,status:"Qualified",value:24000,lastActivity:"12 min ago"},
{id:2,company:"Atlas Health",contact:"Daniel Brooks",title:"Founder",industry:"HealthTech",score:91,status:"Contacted",value:18000,lastActivity:"42 min ago"},
{id:3,company:"Cobalt Studio",contact:"Amelia Ross",title:"CEO",industry:"Design",score:87,status:"New",value:12500,lastActivity:"2 hrs ago"},
{id:4,company:"Vertex Commerce",contact:"Noah Williams",title:"Head of Sales",industry:"Ecommerce",score:82,status:"Qualified",value:31000,lastActivity:"3 hrs ago"},
{id:5,company:"Brightline Legal",contact:"Olivia Patel",title:"Managing Partner",industry:"Legal",score:76,status:"Contacted",value:9500,lastActivity:"Yesterday"},
{id:6,company:"Pioneer Finance",contact:"Ethan Cole",title:"Director",industry:"FinTech",score:71,status:"Lost",value:22000,lastActivity:"2 days ago"}
];
const revenue=[{n:"Mon",v:18},{n:"Tue",v:26},{n:"Wed",v:22},{n:"Thu",v:34},{n:"Fri",v:29},{n:"Sat",v:42},{n:"Sun",v:48}];
const activity=[{n:"Jan",v:32},{n:"Feb",v:45},{n:"Mar",v:38},{n:"Apr",v:61},{n:"May",v:54},{n:"Jun",v:76}];
const nav=[["Overview",LayoutDashboard],["Leads",Users],["Companies",Building2],["Opportunities",Target],["Activities",Activity],["Analytics",CircleDollarSign]] as const;

export default function App(){
 const [section,setSection]=useState("Overview"),[q,setQ]=useState(""),[status,setStatus]=useState("All"),[side,setSide]=useState(false),[ai,setAi]=useState(false),[modal,setModal]=useState(false);
 const filtered=useMemo(()=>leads.filter(x=>(status==="All"||x.status===status)&&Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase())),[q,status]);
 return <div className="app">
 <aside className={side?"sidebar open":"sidebar"}><div className="brand"><span className="brand-mark"><Sparkles size={16}/></span>Pipeline<span className="muted">AI</span></div>
 <div className="workspace"><span className="avatar">TS</span><div><b>Taiwo Studio</b><small>Sales workspace</small></div><ChevronDown size={14}/></div>
 <nav>{nav.map(([name,Icon])=><button key={name} className={section===name?"nav active":"nav"} onClick={()=>{setSection(name);setSide(false)}}><Icon size={17}/>{name}</button>)}</nav>
 <p className="nav-label">WORKSPACE</p><button className="nav"><CalendarCheck size={17}/>Tasks <i>8</i></button><button className="nav"><MessageSquare size={17}/>Messages <i>3</i></button>
 <div className="bottom"><button className="nav"><Settings size={17}/>Settings</button><div className="upgrade"><Sparkles size={16}/><div><b>AI Pro</b><small>Smart prospecting enabled</small></div></div></div></aside>
 {side&&<div className="backdrop" onClick={()=>setSide(false)}/>}
 <main className="main"><header><button className="mobile" onClick={()=>setSide(true)}><Menu/></button><div className="crumb"><Command size={14}/> / {section}</div><div className="head-tools"><div className="search"><Search size={15}/><input placeholder="Search leads, companies..." value={q} onChange={e=>setQ(e.target.value)}/><kbd>⌘ K</kbd></div><button className="bell"><Bell size={17}/><em/></button><span className="profile">TE</span></div></header>
 <div className="content"><div className="page-head"><div><p className="eyebrow">{section==="Overview"?"MONDAY, SEPTEMBER 28, 2026":"SALES WORKSPACE"}</p><h1>{section==="Overview"?"Good morning, Taiwo ✦":section}</h1><p className="sub">{section==="Overview"?"Here's what's happening across your sales pipeline.":"Find, qualify and manage your sales workflow."}</p></div><div className="actions"><button className="secondary" onClick={()=>setAi(true)}><Sparkles size={15}/> AI Assistant</button><button className="primary" onClick={()=>setModal(true)}><Plus size={16}/> Add lead</button></div></div>
 {section==="Overview"?<Overview onAI={()=>setAi(true)} onAdd={()=>setModal(true)}/>:<section className="card"><div className="toolbar"><div className="filters"><button className="filter"><Filter size={14}/> Filters</button>{["All","New","Qualified","Contacted","Won","Lost"].map(s=><button key={s} className={status===s?"chip selected":"chip"} onClick={()=>setStatus(s)}>{s}</button>)}</div><span className="result">{filtered.length} records</span></div><LeadTable data={filtered}/></section>}
 </div></main>
 {ai&&<Assistant close={()=>setAi(false)}/>}
 {modal&&<Modal close={()=>setModal(false)}/>}
 </div>
}

function Overview({onAI,onAdd}:{onAI:()=>void;onAdd:()=>void}){return <><div className="metrics">{[["Pipeline value","$117.0k","+18.4%",Wallet],["Qualified leads","48","+12.8%",Target],["Open opportunities","23","+7.2%",CircleDollarSign],["Meetings booked","16","+21.5%",CalendarCheck]].map(([a,b,c,I])=><div className="metric" key={String(a)}><div className="metric-top"><span>{a}</span><strong><I size={16}/></strong></div><h2>{b}</h2><small><ArrowUpRight size={12}/>{c} <span>vs last month</span></small></div>)}</div>
<div className="charts"><section className="card chart-card"><div className="card-head"><div><h2>Pipeline performance</h2><p>Revenue generated this week</p></div><button className="select">This week <ChevronDown size={13}/></button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>"$"+v+"k"}/><Tooltip/><Area type="monotone" dataKey="v" strokeWidth={3} fillOpacity={.12}/></AreaChart></ResponsiveContainer></div></section>
<section className="card chart-card"><div className="card-head"><div><h2>Lead activity</h2><p>Engagement trend</p></div><span className="live">● Live</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity}><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="v" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section></div>
<section className="card"><div className="card-head pad"><div><h2>Priority leads</h2><p>Highest scoring prospects that need attention</p></div><button className="link">View all <ArrowUpRight size={13}/></button></div><LeadTable data={leads.slice(0,5)}/></section>
<div className="quick"><button onClick={onAI}><Sparkles size={16}/><span><b>Ask your AI sales assistant</b><small>Find follow-ups, draft outreach and summarize pipeline.</small></span><ArrowUpRight size={15}/></button><button onClick={onAdd}><Plus size={16}/><span><b>Add a new prospect</b><small>Capture a lead and prepare it for enrichment.</small></span><ArrowUpRight size={15}/></button></div></>}

function LeadTable({data}:{data:Lead[]}){return <div className="table-wrap"><table><thead><tr><th>Company</th><th>Contact</th><th>Score</th><th>Status</th><th>Value</th><th>Activity</th></tr></thead><tbody>{data.map(l=><tr key={l.id}><td><div className="company"><span>{l.company[0]}</span><div><b>{l.company}</b><small>{l.industry}</small></div></div></td><td><b>{l.contact}</b><small>{l.title}</small></td><td><span className={l.score>84?"score high":"score"}>{l.score}</span></td><td><em className={"status "+l.status.toLowerCase()}>{l.status}</em></td><td><b>$ {l.value.toLocaleString()}</b></td><td><small>{l.lastActivity}</small></td></tr>)}</tbody></table></div>}

function Assistant({close}:{close:()=>void}){return <aside className="drawer"><div className="drawer-head"><b><span className="ai-dot"><Sparkles size={14}/></span>AI Sales Assistant</b><button onClick={close}><X size={18}/></button></div><div className="ai-intro"><div className="ai-big"><Sparkles/></div><h2>Your pipeline copilot</h2><p>Ask about leads, opportunities, follow-ups, or personalized outreach.</p></div><div className="prompts">{["Which leads should I contact today?","Summarize my highest-value opportunities.","Draft a first message for Northstar Labs","Who has not been contacted in 7 days?"].map(x=><button key={x}><MessageSquare size={14}/>{x}<ArrowUpRight size={13}/></button>)}</div><div className="chat"><input placeholder="Ask your sales assistant..."/><button><ArrowUpRight size={16}/></button></div></aside>}

function Modal({close}:{close:()=>void}){return <div className="modal-bg" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW PROSPECT</p><h2>Add lead</h2></div><button onClick={close}><X/></button></div><div className="form"><label>Contact name<input placeholder="Sarah Johnson"/></label><label>Company<input placeholder="Acme Inc."/></label><label>Work email<input type="email" placeholder="sarah@company.com"/></label><label>Job title<input placeholder="CEO / Founder / VP"/></label><label>Industry<select><option>SaaS</option><option>Ecommerce</option><option>HealthTech</option><option>FinTech</option></select></label><label>Estimated value<input placeholder="$25,000"/></label></div><div className="ai-tip"><Sparkles size={15}/><span><b>AI enrichment:</b> connect the existing Python lead API to score this prospect and suggest next actions.</span></div><div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={close}>Create lead</button></div></div></div>}
